In [1]:
#DEKLARASI AWAL
import numpy as np

In [2]:
#1.3.4 
#FLATTENING
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [3]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [5]:
#RESHAPING
a.shape

(2, 3)

In [6]:
b = a.ravel()
b = b.reshape((2, 3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a.reshape((2, -1))    # unspecified (-1) value is inferred

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b[0,0] = 99
a

array([[99,  2,  3],
       [ 4,  5,  6]])

In [10]:
a = np.zeros((3,2))
b = a.T.reshape(3*2)
b[0] = 9
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
#ADDING A DIMENSION
z = np.array([1, 2, 3])
z


z[:, np.newaxis]




z[np.newaxis, :]


array([[1, 2, 3]])

In [13]:
a = np.arange(4*3*2).reshape(4, 3, 2)
a.shape

a[0, 2, 1]

b = a.transpose(1, 2, 0)
b.shape

b[2, 1, 0]

5

In [14]:
b[2, 1, 0] = -1

a[0, 2, 1]

-1

In [15]:
#RESIZING
a = np.arange(4)
a.resize((8,))
a



array([0, 1, 2, 3, 0, 0, 0, 0])

In [16]:
b = a

a.resize((4,)) 

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [17]:
# 1.3.2.5 SORTING DATA
#sorting along an axis
a = np.array([[4, 3, 5], [1, 2, 1]])
b = np.sort(a, axis=1)
b


array([[3, 4, 5],
       [1, 1, 2]])

In [18]:
#in place sort
a.sort(axis=1)
a


array([[3, 4, 5],
       [1, 1, 2]])

In [19]:
#sorting with fancy indexing
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j


array([2, 3, 1, 0])

In [20]:
a[j]

array([1, 2, 3, 4])

In [21]:
#finding minima and maxima
a = np.array([4, 3, 1, 2])
j_max = np.argmax(a)
j_min = np.argmin(a)
j_max, j_min

(0, 2)